### ISSUE TITLE
 User Invitations

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#15]
As an admin, I want to invite users to create accounts in order for them to participate in the hackathon.

**Comment by pierreTklein** [comment]
@pashakondratyev is this done?

**Comment by pashakondratyev** [comment]
In progress, will finish today

**Comment by pierreTklein** [comment]
@pashakondratyev can I close this?

**Comment by pashakondratyev** [comment]
Yes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
