### ISSUE TITLE
ConfirmAccountMiddleware is called during `POST /account` even when user already has invite token

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#161]
**Describe the bug**

According to the `POST /account` middleware, `validateConfirmationTokenWithoutAccount` is called. This checks to see if the account confirmation token exists, and if it does, then it sets the accountType and the confirmation immediately. A following middleware (`sendConfirmAccountEmailMiddleware`) then sends the email to confirm an account.

**Expected behavior**

We do either of two things:

1. Remove `validateConfirmationTokenWithoutAccount`, if it is not useful in any of the user stories.
2. Conditionally send the email only.

**Additional context**

I feel like part of this stems from when a Volunteer, Admin, Sponsor etc. create their account. Not sure though.

**Comment by pashakondratyev** [comment]
validateConfirmationTokenWithoutAccount is there so that if a sponsor with a link which will be addressed with #15 #85 I'll just put a check in the sendConfirmAccountEmailMiddleware
