### ISSUE TITLE
Account name is not populated in email.

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#198]
**Describe the bug**

Emails should have the user's name, however they are not being populated.

**To Reproduce**
1. Send any email to yourself (reset password, or confirm account, for example).

**Screenshots**
![image](https://user-images.githubusercontent.com/17463268/49617693-a2abcc00-f983-11e8-93d4-67755d557518.png)

**Comment by krubenok** [comment]
None of these emails were supposed to have the name in them. Since in some circumstances these emails will be triggered before we collect name information. The only emails that should have name in them are the status updates, these transactional ones should not. cc: @loreina to update copy.
