### ISSUE TITLE
Font not displaying in emails

### ISSUE THREAD

**Issue by loreina** [hackmcgill/hackerAPI#209]
**Describe the bug**

Custom font not displaying in title and button in email signature.

**To Reproduce**

**Expected behavior**

I guess either import Brown into the inline HTML or use Hind since it's a Google font. Will inspect later.

**Screenshots**

![image](https://user-images.githubusercontent.com/23108291/49850702-7beafc80-fdac-11e8-9b98-9b8b144cf339.png)

**Additional context**

**Comment by pierreTklein** [comment]
@loreina can I close this?

**Comment by loreina** [comment]
@pierreTklein it was never fixed 😕
