### ISSUE TITLE
Staff-Hacker information update

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#21]
As a staff member, I want to scan hackers' QR codes in order to update their information.

**Comment by pierreTklein** [comment]
On the front-end, this would work in this way:
- scan QR code
- translate QR code to Hacker ID
- make POST request to update Hacker detail for status

**Comment by pierreTklein** [comment]
there should be a route that has restricted access to updating a hacker:
List of things it should do: 
* Check in a user

**Comment by pierreTklein** [comment]
Actually, this is a duplicate of #14
