### ISSUE TITLE
Modify an existing role

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#220]
### Route name

Update Role

### Short description

Modify an existing role by adding or removing routes.

#### Body
| Attribute name | Type |
|----------------|------|
| roleName | String |
| addRoutes | `{uri: string, requestType: enum of request types}` |
| removeRoutes | `{uri: string, requestType: enum of request types}` |

#### Authentication required

Must be logged in.

#### Authorization required

Must be a staff account.

**Comment by YiFeiZhang2** [comment]
Assuming that addRoutes and removeRoutes are both arrays of routes.
