### ISSUE TITLE
Make Github URL optional

### ISSUE THREAD

**Issue by loreina** [hackmcgill/hackerAPI#222]
**Describe the bug**
Make Github URL optional

**To Reproduce**

**Expected behavior**
In the application, including a Github URL should be optional instead of required.

**Screenshots**

**Additional context**

Beginners might not have a Github URL to use and making an account that's entirely blank just for the purposes of applying doesn't make much sense.

**Comment by pierreTklein** [comment]
Just checked the api, the api doesn't enforce github anymore. Will reflect this on frontend.
