### ISSUE TITLE
Invite Email typos

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#253]
**Describe the bug**

I am staff, yet it says "hacker dashboard"
![image](https://user-images.githubusercontent.com/17463268/50458817-47f40780-0966-11e9-9ea5-ca6b33187adc.png)

**Comment by krubenok** [comment]
I don't think this is an issue. We have been marketing this as the "hacker dashboard" to our sponsors ors the whole time so it's probably ok?

**Comment by pierreTklein** [comment]
Alright, I’ll close this issue then.
