### ISSUE TITLE
Batch actions

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#254]
# Idea

Perform a batch action on the database (such as accepting hackers) that fit a certain search criteria. This would be an extension of the search functionality, or perhaps be another route that uses some search functionalities. 

Ideally, the architecture is extensible so we can add another batch action to this.

## Batch actions:

- Send [Acceptance | Waitlist | Reminder ] email to set of hackers 
- Change status to set of hackers

## Permissions:

- Admin only

**Comment by MrHarshPatel** [comment]
HCK-18 #comment Testing

**Comment by loreina** [comment]
Associated with #276
