### ISSUE TITLE
Make parsePatch method generic

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#280]
Can we extract this into a general service method that takes original object and a schema, and returns the attributes that match the schema?

_Originally posted by @pierreTklein in https://github.com/hackmcgill/hackerAPI/pull/277_

**Comment by Ty-Won** [comment]
Drop some roast :fire: if there's an issue! Sorry for the delay, been busy with work on boarding but more should roll out slowly :') :+1: If its all good, I'll start making use of the service to replace the manual parsePatch Functions across the middleware

**Comment by pierreTklein** [comment]
Is there a PR for this?

**Comment by Ty-Won** [comment]
No I wasnt sure if I should have created a PR since the method needs to be called across different services and I just started with the implementation of the method to see if it was alright before putting it across the api

**Comment by Ty-Won** [comment]
*across different middleware

**Comment by krubenok** [comment]
Maybe a draft PR is the best way? https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by Ty-Won** [comment]
Yeah sure that's true!
