### ISSUE TITLE
User Email

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#30]
As an admin, I would like to send emails to a list of people in order to inform them about hackathon related information

**Comment by pierreTklein** [comment]
Types of emails:
- Waitlist
- Accept
- Week-of-email: reminder, packing list, etc.
- Reject

**Comment by pierreTklein** [comment]
See #74 for sending an email when a user's status is changed.

**Comment by pierreTklein** [comment]
Closing this issue. @krubenok can you make a mirror issue on https://github.com/hackmcgill/hackerAPI-frontend/issues?
