### ISSUE TITLE
Create unit tests for current routes and check for correctness

### ISSUE THREAD

**Issue by YiFeiZhang2** [hackmcgill/hackerAPI#31]
The goal is to finish up unit tests for the rest of the current routes and methods by mid next week (August 8 ish). To do this, unit test setup will have to be created. The full list is as follows:

Unit test setup to be done:
- skill.test.util.js
- sponsor.test.util.js
- staff.test.util.js
- team.test.util.js
- volunteer.test.util.js

The unit tests will cover routes for:
- accounts
- auth
- hacker
-team

The unit tests will cover services for:
- accounts
- auth
- database
- hacker
- permission
- skill
- team

The unit tests will cover middleware for:
- account validator
- hacker validator
- team validator
- validator helper
- account middleware
- auth middleware

The unit tests will cover controllers for: 
- accounts
- auth
- hacker

Unit tests for models may be needed

**Comment by pierreTklein** [comment]
current bug in tests with invalid routes
