### ISSUE TITLE
Design and create routes for create functions

### ISSUE THREAD

**Issue by YiFeiZhang2** [hackmcgill/hackerAPI#32]
Design route grouping and create the routes for the creates for all models. This will happen after writing unit tests for the current methods (issue 31). The expectation is that filter will be complete by this time, and permissions will be fleshed out. The projected timeline for this is 2 weeks.

**Comment by pierreTklein** [comment]
What create routes do we have left for this? @YiFeiZhang2

**Comment by pierreTklein** [comment]
* Bus
* POST Role + RoleBinding
* PATCH Sponsor
* All of STAFF
* GET of Post
