### ISSUE TITLE
Integrate OAuth for login

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#34]
Enabling OAuth support for passport.js to allow for logins with Google, Facebook, Twitter, Github, LinkedIn, etc....

**Comment by idodin** [comment]
Hi Hack McGill friends! I mentioned to @krubenok that I was looking to this for our system so I'd be down to take a whack at this for you guys too, after exams :)

**Comment by krubenok** [comment]
Thanks @idodin! Hopefully this and https://github.com/hackmcgill/hackerAPI-frontend is helpful in creating your portal!

**Comment by pierreTklein** [comment]
@idodin any updates?

**Comment by idodin** [comment]
@pierreTklein Ah, actually got started last night, sorry for the delay - was taking it easy for a bit after exams and pre-Ramadan. I don't imagine it will take long at all though.

**Comment by idodin** [comment]
Hey guys! I haven't forgotten about this, I've just been struggling to find time for anything while running Summer Training (and taking BIOL 202 haha). I'll keep trying to make time, but, if someone else is willing to take this issue, please do not hesitate to do so - I don't want to delay you guys anymore than I already have.
