### ISSUE TITLE
Test refactor - Spec below

### ISSUE THREAD

**Issue by YiFeiZhang2** [hackmcgill/hackerAPI#464]
Problem:
 * Entities from different models may need to be referenced during testing. We need a clear, understandable, and scalable means of creating new entities that reference each other. 
 * Current methodology relies on convention. The convention only captures major testing scenarios (stored/invalid/new documents), and breaks down when testing for specific situations (Hacker that's been waitlisted).
 * Current methodology repopulates all entities during every test, which is a very slow process. Most of these entities are not used.

Goals:
 * It should be easy to use the correct documents in a test. If the test is to successfully move a hacker into a team, an engineer should easily be able to find an account to log in, a hacker, and a team such that:
   * The logged in account is the account of the hacker
   * The hacker was not already in the team
   * The hacker has the capability of joining the team (hacker application fully completed)
   * The team is not full
 * Tests should not load unecessary documents into the database, but be able to load documents with enough granularity to test specific cases such as:
   * Hacker waitlisted
   * Non-confirmed account
   * Other situations requiring specific fields from certain documents
 * Tests should load the data on the fly. The best case scenario would be that the data is created on the fly as well.
 * Generating and/or loading data should be simple to use. A developer should not have to enter in data for specific fields if those fields are not explicitly tested. For example, a developer looking to test a hacker should not have to enter in the firstName model of the associated account. However, they should be given the option to manually set the attribute of any field they desire.

Metrics:
 * Ease of use for developers - personal feedback
 * Robustness of testing: Can the method generate data for every testing scenario?
 * Time: How much faster is the method compared to the current one?

Out of Scope:
 * Major database model redesign
 * Creating new test cases, or changing what the current tests test: The refactor is limited to streamlining the process of generating and using entities for the tests.

Context:
 * Situation: Developer created a new route that allows a `Staff` to change the status of all `Hackers` in a `Team` to a particular status, as long as all the `Hackers` have finished their applications. The test will include:
   * Success case
   * `Staff` credentials are incorrect
   * Logged in account is not a `Staff` account
   * `Team` does not exist
   * Some `Hackers` on the team have not finished their application
 * The developer should be able to generate all documents needed to do these tests, with specific information including:
   * Non-staff account
   * `Staff` account
   * `Team`, associated `Hackers`, and `Accounts` linked to those `Hackers`
   * All `Rolebindings`
   * `Hackers` without a completed application (their status is None)

Proposal:
 * Create entities recursively, allowing field values to be passed through input. For example, `createHacker` would create the `Hacker` document, as well as the associated `Account`. It could take in optional field values such as `status` if those fields need to be set to a specific value. Otherwise, the values would be generated randomly.
 * Entities would be created and saved to the database on an as-needed basis. 
 * Database would still be cleared after each test to maintain a fixed starting state.

**Comment by pierreTklein** [comment]
@andyjung-dev def an interesting idea.
