### ISSUE TITLE
Create preset hacker info access permission profiles

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#49]

**Comment by krubenok** [comment]
| Action | Description | Route |
| -------- | ------------- | :------- |
| View Basic Hacker Info | View first name, last name, email, dietary restrictions, shirt size, bus, status, school, team | <leave blank> | |
| View Hacker Job Info | View first name, last name, email, status, school, team, job interest, skills, portfolio URLs | <leave blank> | |
| View full application | View and Edit View first name, last name, email, dietary restrictions, shirt size, bus, status, school, team, job interest, skills, portfolio URLs, essay, comments, gender | |
