### ISSUE TITLE
Contribution request from Business Administration students

### ISSUE THREAD

**Issue by SedaCTN** [hackmcgill/hackerAPI#647]
Dear contributors of hackerAPI,

Together with a group of 3 students we are working on a project for our studies. We would like to contribute to hackerAPI in a way that fits your needs, that does not involve coding.

We can do one of the following contributions:

- Test the app and give feedback from our point of view (or i.e. 65+)
- Make a small survey about the app and distribute it amongst our peers at the university.
- Anything else that fits your needs.

We would like to interview some of your contributors for some background information on the project.

If some of you could help us out we would really appreciate this. We would like a quick response since we have to move on with our project.

Thank you in advance,

Seda and team mates.

**Comment by loreina** [comment]
@SedaCTN This sounds great! Can you reach out to dev@mchacks.ca?
