### ISSUE TITLE
Add `npm run seed` to CI/CD

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#653]
With @pierreTklein's work on restoring confidence in the `npm run seed` command (#652, pending a successful manual deployment). I believe we should work to automate the database readiness steps involved in promoting new versions of the API to production. 

I propose adding a Github Actions workflow that will do the following: 
1. SSH into a server to create a mongodump snapshot of the production database and report back the integrity of the backup.  
2. Run `npm run seed` on the production database 
3. Report back into the team Slack with references to these events.

**Comment by loreina** [comment]
dup: #660. will fit this into transition to Github Actions, thanks @krubenok :)
