### ISSUE TITLE
Travel API not complete

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#667]
**Describe the bug**

1. Hackers cannot actually submit a request for reimbursement because they lack the role binding for this.
2. The backend validation for travel reimbursement is up to 3,000 dollars
3. Hackers cannot actually update their request for reimbursement.

As a result, the Travel page in the UI is blank, because the travel schema was never created.

We should either update the travel request internally with each application update, or work on the API endpoints.

**Comment by logan-r** [comment]
Yeah, travel needs some serious overhaul (plus an interface on frontend for organizers to review and hand out disbursements).
Since this year's hackathon is remote, we won't be using travel at all, so it'll be lower priority but still in needs a lot of work.

**Comment by tektaxi** [comment]
could reopen in the future if/when travel reimbursement comes back, closed for now as we are not reimbursing for travel in McHacks 12 (and haven't since pre covid).
