### ISSUE TITLE
Investigate test suite for performance issues

### ISSUE THREAD

**Issue by jamesxu123** [hackmcgill/hackerAPI#691]
This has a pretty big impact on our CI/CD pipeline and it would be very nice to figure out why it's taking so long to run.

- Currently takes a very long time to run
- Determine ways to improve performance
- Implement fixes

**Comment by pierreTklein** [comment]
AFAIK, we destroy and then reload the entire test database. This means deleting and then loading hundreds of accounts, teams, applications, etc.

Maybe we can instead just manually load all of the necessary information for each test? This means a ton more code per test, but it could be worth it. 

I would also investigate whether it's possible to run multiple tests at the same time, or use a different, more efficient testing framework.
