### ISSUE TITLE
Add time-based hacker object creation statistics

### ISSUE THREAD

**Issue by jamesxu123** [hackmcgill/hackerAPI#693]
Modify the stats route so that it also parses all hacker objects to retrieve object creation time and returns this data in a suitable format for graphing

- Stats code should be located in https://github.com/hackmcgill/hackerAPI/blob/dev/services/hacker.service.js
- Relevant model: https://github.com/hackmcgill/hackerAPI/blob/dev/models/hacker.model.js

**Comment by NamamiShanker** [comment]
Hey! I am new and would like to contribute. How can I get started?
