### ISSUE TITLE
FR: Integrated Judging

### ISSUE THREAD

**Issue by krubenok** [hackmcgill/hackerAPI#803]
In a similar vein to #802, it seems like there's an opportunity to ingrate the project judging and submission process into the main API and dashboard. While Gavel has some excellent math behind it, the user management and project onboarding leave a lot to be desired. If the information is already present in the main API, it seems logical to integrate this functionality. 

In terms of backend support, there'd be a few parts involved. This comes to mind as a start: 

- Submitting a project by a team of hackers with all relevant fields to describe a project.
   - Open question of how this would work in hackathons where there is IRL expo style judging, seems cautious to also have everything submitted electronically. 
   - This would remove the need to devpost which has **always** been a huge point of day of confusion for hackers on Sundays. 
- Create a new role of user "judge" that could be superimposed onto other types of users (example: volunteers, organizers, and sponsors could also be judges in addition to their normal role)
- Similar to hacker admittance, implement similar math to gavel to record pairwise comparisons and product rankings
    - As a bonus implement support for sub-categories within the pairwise comparison for sponsor and category prizes  
- Implement project querying and listing in the same manner that admins and browse the list of hackers.
- Implement support for prize claiming as part of the API
   - This (for the last 8 McHacks, I'm not even kidding) has been a huge point of annoyance for hackers who won prizes. Collecting addresses, delivery information, etc... when people have won a prize. 

In terms of front end support, I expect that most of the UI would be very similar to the hacker admission UI for pairwise comparison so decent value for that work. 

cc: @pierreTklein am I missing some things?

**Comment by brarsanmol** [comment]
I agree with the sentiment around this, once again I had a conversation with Logan about this. We have some of the groundwork laid out for submissions and such, we should integrate our own version of judging (Gavel develop has plateaued so I don't for-see any groundbreaking changes occurring there).

I don't for-see this is as something that dev team can take on for the 2022 - 2023 year, more long term.
