### ISSUE TITLE
Invite links to create account with tokens

### ISSUE THREAD

**Issue by pierreTklein** [hackmcgill/hackerAPI#85]
- Users who create an account should be sent an email to create the specific profile of account that they signed up for.
- Examples: 
As a hacker, when I create an account, I should receive an email to confirm my account with a link to fill out my hacker profile. This link contains an auth token which is used to allow the given user to create ONE hacker profile with the associated account.

This is the same flow for all other types of accounts.

Flow for account creation:

[ create account ] -> [ get email to create hacker / sponsor / volunteer account ] -> [ click link, which contains auth token in URL ] -> [ front-end takes auth token and passes that to the API with account data ] -> [ backend validates token, creates account, makes token no longer valid ]

**Comment by pierreTklein** [comment]
Estimate:
- Hacker registration: Thursday night
- Sponsor, Admin, Volunteer, Staff registration: Friday night

**Comment by pierreTklein** [comment]
@pashakondratyev can we close this story?

**Comment by pashakondratyev** [comment]
Still need to do other types of accounts

**Comment by pierreTklein** [comment]
Okay

**Comment by pashakondratyev** [comment]
I think its done with PR 167

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
