### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by jackyyzhang03** [hackmcgill/hackerAPI#925]
Currently some unit tests are failing, we should investigate and fix them as necessary.

**Comment by msohaill** [comment]
Seems there are a few commits that have caused the unit tests to break. I'll list them and what I've been able to gather.
 - e045828: Introducing `secure` option causes authentication issues with passport and chai during unit tests. **Resolution:** `secure` should be true in non-test environments (i.e., `secure: !Services.env.isTest()`
 - 01aec67: Some validation left out when introducing accommodation reason (i.e., no upper limit on amount any more). Renaming of field ("application.accommodation.travel" => "application.accomodation.travel.amount") caused issues with tests. **Resolution:** re-introduce upper limit of 100 on travel amount and rename validation fields in tests.
 - 2e3fd15: Disabling this validation led to some issues in tests that are expected to fail if the hacker's account is not confirmed. **Resolution:** UNKNOWN. We could obviously enable the validation, but not sure if that leads to problems elsewhere. Other alternative is to remove the corresponding tests.
 - a5e29a2: Same as above. **Resolution:** Same as above, not sure what to do.
