### ISSUE TITLE
Update error messages to be more informative

### ISSUE THREAD

**Issue by YiFeiZhang2** [hackmcgill/hackerAPI#99]
Update the error messages in different controllers. The goal is to create more descriptive messages that give more of an idea to what the error is and to make sure that we produce the same error message for the same error. For example, failure to retrieve a hacker due to an invalid id should produce the same error as a failure to retrieve a sponsor due to an invalid id except for replacing 'hacker' with 'sponsor'.

**Comment by pierreTklein** [comment]
@YiFeiZhang2 Can I close this?
